spring:
  datasource:
    dynamic:
      primary: master
      tenanted: false
      tenant-schema: camundatest
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
#          ## mysql数据源
          url: jdbc:mysql://127.0.0.1:3306/camundatest?characterEncoding=UTF-8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
#        123456:
#          type: com.zaxxer.hikari.HikariDataSource
#          ## mysql数据源
#          url: jdbc:mysql://127.0.0.1:3306/camundatest_123456?characterEncoding=UTF-8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#          username: root
#          password: root
#          driver-class-name: com.mysql.jdbc.Driver
#        dm:
#          type: com.zaxxer.hikari.HikariDataSource
#          ## 达梦数据源
#          username: SYSDBA
#          password: SYSDBA001
#          driver-class-name: dm.jdbc.driver.DmDriver
#          url: jdbc:dm://192.168.0.124:30236?schema=camundatest&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&compatibleMode=mysql&clobAsString=true&keyWords=reference,percent

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/camundatest?characterEncoding=UTF-8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    dynamic:
#      tenanted: false
#      tenant-schema: camundatest



camunda:
  bpm:
    database:
      type: mysql
      schema-update: true # 是否自动建表，但我测试为true时，创建表会出现，因此还是改成false由手工建表。
    auto-deployment-enabled: false # 自动部署 resources 下的 bpmn文件
    admin-user:
      id: admin
      password: 123456
    eventing:
      execution: true
      history: true
      task: true
server:
  port: 8081


#下面的使用默认的h2数据库
#spring:
#  datasource:
#    url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=1000;LOCK_TIMEOUT=10000
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#camunda:
#  bpm:
#    database:
#      type: h2 #可改成 mysql
#      schema-update: true
#    auto-deployment-enabled: false # 自动部署 resources 下的 bpmn文件
#    admin-user:
#    id: admin
#    password: 123456
#